set_debug_logging:
  name: Set logging level
  description: "Set the logging level for the Sure Petcare integration and library."
  fields:
    level:
      description: Log level to set
      required: true
      selector:
        select:
          options:
            - DEBUG
            - INFO

set_control:
  name: Set control values
  description: |
    Set one or more control fields on the SurePetcare device. You can update fields such as training_mode, fast_polling, bowls, lid, tare, etc. Provide a dictionary with the fields you want to set. Example:
    {
        training_mode: 1
        fast_polling: true
        bowls:
          settings:
            - food_type: 1
              target: 50
            - food_type: 1
              target: 30
          type: 0
    }
  fields:
    device_id:
      description: Target device registry id to control.
      required: true
      selector:
        device:
          integration: surepetcare
    control:
      description: Dictionary of control fields to set (e.g. training_mode, fast_polling, bowls, etc).
      required: true
      example: {"training_mode": 1, "fast_polling": true, "bowls": {"settings": [{"food_type": 1, "target": 50}], "type": 0}}
      selector:
        object: {}
set_tag:
  name: Update Pet Device access.
  description: Set the tag for a device.
  fields:
    device_id:
      description: Target device registry id.
      required: true
      selector:
        device:
          integration: surepetcare
    pet_id:
      name: Pet ID
      description: Target Pet registry id to update
      required: true
      selector:
        device:
          integration: surepetcare
    action:
      description: Action to perform on the tag (add or remove)
      required: true
      selector:
        select:
          options:
            - ADD
            - REMOVE

set_pet_access_mode:
  name: Set Pet Access Mode
  description: Sets a pet's profile to "indoor only" to prevent passthrough of flap.
  fields:
    pet_id:
      name: Pet
      description: Pet registry id to modify access mode.
      required: true
      example: 123456
      selector:
        device:
          integration: surepetcare

    device_id:
      name: Device (Flap or Feeder)
      description: The device registry id of Flap/Feeder to modify access on.
      required: true
      example: 123456
      selector:
        device:
          integration: surepetcare
    profile:
      name: Profile
      description: Pet access profile (e.g. indoor, outdoor, etc.). Part of PetDeviceLocationProfile. Use with care.
      required: true
      selector:
        select:
          options:
            - NO_RESTRICTION
            - INDOOR_ONLY
  
set_pet_position:
  name: Set pet position
  description: Set a pet's position to inside or outside.
  fields:
    pet_id:
      name: Pet
      description: Pet registry id to modify access mode.
      required: true
      selector:
        device:
          integration: surepetcare

    action:
      description: Action to perform on the pet's position (add or remove)
      required: true
      selector:
        select:
          options:
            - INSIDE
            - OUTSIDE